# Generated by Django 5.1.5 on 2025-02-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('W', 'Watch'), ('BI', 'Bueaty item'), ('ELE', 'Electronic item'), ('B', 'Bags')], max_length=200),
        ),
    ]
